"""add market_price_per_kg to fish_farms

Revision ID: 47855b39eaff
Revises: c45f54380c61
Create Date: 2026-06-23 07:56:56.174990
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47855b39eaff'
down_revision = 'c45f54380c61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish_farms', sa.Column('market_price_per_kg', sa.Float(), server_default='95.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish_farms', 'market_price_per_kg')
    # ### end Alembic commands ###
