"""Add community fields to MediaUpload

Revision ID: 59579fa79109
Revises: a1cf88bc1b6d
Create Date: 2026-05-08 17:58:52.291021
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59579fa79109'
down_revision = 'a1cf88bc1b6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_uploads', sa.Column('is_community', sa.Boolean(), nullable=False))
    op.add_column('media_uploads', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('media_uploads', sa.Column('post_text', sa.Text(), nullable=True))
    op.create_index(op.f('ix_media_uploads_is_community'), 'media_uploads', ['is_community'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_uploads_is_community'), table_name='media_uploads')
    op.drop_column('media_uploads', 'post_text')
    op.drop_column('media_uploads', 'title')
    op.drop_column('media_uploads', 'is_community')
    # ### end Alembic commands ###
