"""add_rbac_models

Revision ID: 903e099e7a8f
Revises: edae85b0d849
Create Date: 2026-05-17 03:17:52.524362
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903e099e7a8f'
down_revision = 'edae85b0d849'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['fish_farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_members_farm_id'), 'farm_members', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farm_members_user_id'), 'farm_members', ['user_id'], unique=False)
    op.create_table('team_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('inviter_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['fish_farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invitations_email'), 'team_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_team_invitations_farm_id'), 'team_invitations', ['farm_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_inviter_id'), 'team_invitations', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_token'), 'team_invitations', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_invitations_token'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_inviter_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_farm_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_email'), table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index(op.f('ix_farm_members_user_id'), table_name='farm_members')
    op.drop_index(op.f('ix_farm_members_farm_id'), table_name='farm_members')
    op.drop_table('farm_members')
    # ### end Alembic commands ###
