"""Init Fish Models

Revision ID: a1cf88bc1b6d
Revises: 
Create Date: 2026-05-08 17:35:23.483228
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cf88bc1b6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('privileges', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('avatar_sha256', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('direct_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_messages_created_at'), 'direct_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_direct_messages_read_at'), 'direct_messages', ['read_at'], unique=False)
    op.create_index(op.f('ix_direct_messages_receiver_id'), 'direct_messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_direct_messages_sender_id'), 'direct_messages', ['sender_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_submitted_at'), 'feedbacks', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_table('fish_farms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fish_farms_user_id'), 'fish_farms', ['user_id'], unique=False)
    op.create_table('friend_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', 'status', name='uq_friend_request_pending_state')
    )
    op.create_index(op.f('ix_friend_requests_created_at'), 'friend_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_friend_requests_receiver_id'), 'friend_requests', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_sender_id'), 'friend_requests', ['sender_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_status'), 'friend_requests', ['status'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_one_id', sa.String(length=36), nullable=False),
    sa.Column('user_two_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_one_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_two_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_one_id', 'user_two_id', name='uq_friendship_pair')
    )
    op.create_index(op.f('ix_friendships_created_at'), 'friendships', ['created_at'], unique=False)
    op.create_index(op.f('ix_friendships_user_one_id'), 'friendships', ['user_one_id'], unique=False)
    op.create_index(op.f('ix_friendships_user_two_id'), 'friendships', ['user_two_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('ponds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('size_sq_meters', sa.Float(), nullable=True),
    sa.Column('stocking_density', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['fish_farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ponds_farm_id'), 'ponds', ['farm_id'], unique=False)
    op.create_table('environmental_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pond_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dissolved_oxygen', sa.Float(), nullable=True),
    sa.Column('ammonia_level', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('ph_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_data_pond_id'), 'environmental_data', ['pond_id'], unique=False)
    op.create_index(op.f('ix_environmental_data_timestamp'), 'environmental_data', ['timestamp'], unique=False)
    op.create_table('media_uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pond_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('upload_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pond_id'], ['ponds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_uploads_pond_id'), 'media_uploads', ['pond_id'], unique=False)
    op.create_index(op.f('ix_media_uploads_upload_time'), 'media_uploads', ['upload_time'], unique=False)
    op.create_index(op.f('ix_media_uploads_user_id'), 'media_uploads', ['user_id'], unique=False)
    op.create_table('analysis_histories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('suitability_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['media_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_histories_analysis_date'), 'analysis_histories', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_analysis_histories_upload_id'), 'analysis_histories', ['upload_id'], unique=True)
    op.create_table('community_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['community_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['media_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_comments_created_at'), 'community_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_comments_parent_comment_id'), 'community_comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_community_comments_upload_id'), 'community_comments', ['upload_id'], unique=False)
    op.create_index(op.f('ix_community_comments_user_id'), 'community_comments', ['user_id'], unique=False)
    op.create_table('community_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['media_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'user_id', name='uq_community_likes_upload_user')
    )
    op.create_index(op.f('ix_community_likes_created_at'), 'community_likes', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_likes_upload_id'), 'community_likes', ['upload_id'], unique=False)
    op.create_index(op.f('ix_community_likes_user_id'), 'community_likes', ['user_id'], unique=False)
    op.create_table('species_identifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['media_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_identifications_upload_id'), 'species_identifications', ['upload_id'], unique=False)
    op.create_table('biological_healths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('health_status', sa.String(length=100), nullable=False),
    sa.Column('disease_type', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['analysis_histories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biological_healths_history_id'), 'biological_healths', ['history_id'], unique=False)
    op.create_table('community_comment_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['community_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_community_comment_likes_comment_user')
    )
    op.create_index(op.f('ix_community_comment_likes_comment_id'), 'community_comment_likes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_community_comment_likes_created_at'), 'community_comment_likes', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_comment_likes_user_id'), 'community_comment_likes', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('comment_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['comment_id'], ['community_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['media_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_actor_user_id'), 'notifications', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_comment_id'), 'notifications', ['comment_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_kind'), 'notifications', ['kind'], unique=False)
    op.create_index(op.f('ix_notifications_post_id'), 'notifications', ['post_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['analysis_histories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_history_id'), 'reports', ['history_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_history_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_post_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_kind'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_comment_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_actor_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_community_comment_likes_user_id'), table_name='community_comment_likes')
    op.drop_index(op.f('ix_community_comment_likes_created_at'), table_name='community_comment_likes')
    op.drop_index(op.f('ix_community_comment_likes_comment_id'), table_name='community_comment_likes')
    op.drop_table('community_comment_likes')
    op.drop_index(op.f('ix_biological_healths_history_id'), table_name='biological_healths')
    op.drop_table('biological_healths')
    op.drop_index(op.f('ix_species_identifications_upload_id'), table_name='species_identifications')
    op.drop_table('species_identifications')
    op.drop_index(op.f('ix_community_likes_user_id'), table_name='community_likes')
    op.drop_index(op.f('ix_community_likes_upload_id'), table_name='community_likes')
    op.drop_index(op.f('ix_community_likes_created_at'), table_name='community_likes')
    op.drop_table('community_likes')
    op.drop_index(op.f('ix_community_comments_user_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_upload_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_parent_comment_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_created_at'), table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index(op.f('ix_analysis_histories_upload_id'), table_name='analysis_histories')
    op.drop_index(op.f('ix_analysis_histories_analysis_date'), table_name='analysis_histories')
    op.drop_table('analysis_histories')
    op.drop_index(op.f('ix_media_uploads_user_id'), table_name='media_uploads')
    op.drop_index(op.f('ix_media_uploads_upload_time'), table_name='media_uploads')
    op.drop_index(op.f('ix_media_uploads_pond_id'), table_name='media_uploads')
    op.drop_table('media_uploads')
    op.drop_index(op.f('ix_environmental_data_timestamp'), table_name='environmental_data')
    op.drop_index(op.f('ix_environmental_data_pond_id'), table_name='environmental_data')
    op.drop_table('environmental_data')
    op.drop_index(op.f('ix_ponds_farm_id'), table_name='ponds')
    op.drop_table('ponds')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_friendships_user_two_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_one_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_created_at'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_requests_status'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_sender_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_receiver_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_created_at'), table_name='friend_requests')
    op.drop_table('friend_requests')
    op.drop_index(op.f('ix_fish_farms_user_id'), table_name='fish_farms')
    op.drop_table('fish_farms')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_submitted_at'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_direct_messages_sender_id'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_receiver_id'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_read_at'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_created_at'), table_name='direct_messages')
    op.drop_table('direct_messages')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
