"""Add average_fish_weight_grams to FishFarm

Revision ID: a51a65e1ad65
Revises: 1956696d51e4
Create Date: 2026-06-29 05:06:27.232821
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51a65e1ad65'
down_revision = '1956696d51e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fish_farms', sa.Column('average_fish_weight_grams', sa.Float(), server_default='450.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fish_farms', 'average_fish_weight_grams')
    # ### end Alembic commands ###
