"""add_title_to_scan_history

Revision ID: b7d2aa495d1b
Revises: 20260418_0009
Create Date: 2026-04-25 16:54:35.742314
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d2aa495d1b'
down_revision = '20260418_0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_history', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_history', 'title')
    # ### end Alembic commands ###
