"""add name to pond

Revision ID: c45f54380c61
Revises: 903e099e7a8f
Create Date: 2026-06-23 06:18:59.027536
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45f54380c61'
down_revision = '903e099e7a8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ponds', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ponds', 'name')
    # ### end Alembic commands ###
