"""Add fish_count

Revision ID: e2909dd0ed4d
Revises: a51a65e1ad65
Create Date: 2026-06-29 11:18:31.167625
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2909dd0ed4d'
down_revision = 'a51a65e1ad65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_histories', sa.Column('fish_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_histories', 'fish_count')
    # ### end Alembic commands ###
